== Prozessverwaltung

=== Grundfunktionalität

Die Prozessverwaltung liest das von der Skriptverwaltung bereitgestellte
StartStopp-Skript. Wenn ein gültiges Skript zur Verfügung steht, werden für die
definierten Inkarnationen Applikationen erzeugt und entsprechend den
Abhängigkeiten und den Regeln ausgeführt.

Die Applikationen werden als individuelle Instanzen ausgeführt und passen ihren
Status entsprechend den Bedingungen und den Rückmeldungen aus dem Betriebssystem
an.

Folgende Statuswerte sind für eine Applikation vorgesehen:

* _INSTALLIERT_: ist der initiale Status des Applikationsobjekts
* _STARTENWARTEN_: die Applikation soll gestartet werden, die  Ausführung wird 
      aber durch mindestens einen der folgenden Punkte verhindert:
** die Startbedingung ist nicht erfüllt
** die Startbedingung für die Applikation ist erfüllt, es
      ist aber eine Wartezeit bis zum Start definiert
** eine zyklisch auszuführende Applikation wartet auf den nächsten Startzeitpunkt      
* _GESTARTET_: die Applikation wurde gestartet, es wurde jedoch noch keine 
   Initialisierungsmeldung über den Datenverteiler geliefert.
* _INITIALISIERT_: die Applikation ist aktiv und hat über den Datenverteiler eine
  Initialisierungsmeldung geliefert
* _STOPPENWARTEN_: die Applikation soll gestoppt werden, die Ausführung wird
     aber durch eine der folgenden Bedingungen verhindert:
** die Stopbedingung ist nicht erfüllt
** die Stoppbedingung für die Applikation ist erfüllt, es ist aber eine Wartezeit 
    bis zum Stopp definiert
** der zugehörige Betriebssystemprozess wurde noch nicht beendet
* _GESTOPPT_: die Applikation wurde beendet

[plantuml, "applikations_status"]
----
title Zustandsdiagramm für Applikationen in StartStopp \n

[*] --> INSTALLIERT
INSTALLIERT ---> STARTENWARTEN: Manueller oder automatischer Start
STARTENWARTEN ---> GESTARTET: Startbedingungen erfüllt
GESTARTET ---> GESTOPPT: Fehler beim Starten
GESTARTET ---> STOPPENWARTEN: Stopp angefordert
GESTARTET --> INITIALISIERT: Rückmeldung vom DAV
STOPPENWARTEN  ---> GESTOPPT: Stoppbedingungen erfüllt, Systemprozeß beendet
STOPPENWARTEN  ---> STARTENWARTEN: Stoppbedingungen erfüllt,\nzyklischer Prozeß wartet auf nächste Ausführung
STARTENWARTEN ---> GESTOPPT: Stopp angefordert
INITIALISIERT --> STOPPENWARTEN: Stopp angefordert

note left of STOPPENWARTEN
    Kann per Request übersprungen werden
end note

note right of STARTENWARTEN
    Kann per Request übersprungen werden
end note

----
