#%RAML 1.0
title: StartStopp
version: v1
baseUri: https://api.startstopp.sys.bsvrz.de
mediaType: application/json
types:
  StartStoppSkript: !include schema/startstoppskript.schema.json
  StatusResponse: !include schema/statusresponse.schema.json

/skripte:
  description: Zugriff auf die für StartStopp vorliegenden Skripte
  /current:
    description: Liefert das aktuelle im StartStopp verwendete Skript
    get:
      responses:
        200:
          body:
            application/json:
              type: StartStoppSkript
        202:
          body:
            application/json:
              type: StartStoppSkript
    /status:
      get:
        responses:
          200:
            body:
              application/json:
                type: StatusResponse

/applikationen:
  description: Zugriff auf die in StartStopp verwalteten Applikationen
