#%RAML 1.0
title: StartStopp
version: v1
baseUri: https://api.startstopp.sys.bsvrz.de
mediaType: application/json
types:
   StartStoppKonfiguration:
     schema: !include startstoppkonfiguration.json

/startstoppkonfigurationen:
  description: The search resource
  get:
    responses:
      200:
        body:
          application/json:
            type: StartStoppKonfiguration
  
