FORMAT: 1A
HOST: https://api.svz-bw.de

# VerkehrsInfo BW

Beschreibt die Web-API, die von der App VerkehrsInfo BW zum Abruf von Daten vom Server verwendet wird.

## Data Structures

###  Wgs84

+ lat: 49.77116 (number, required) - Geographische Breite in Grad.
+ lon: 9.574007 (number, required) - Geographische Breite in Grad.

### Offset

+ x: 10 (number, required) - Verschiebung in x-Richtung (Ost negativ, West positiv) in Pixel.
+ y: 15 (number, required) - Verschiebung in y-Richtung (Nord negativ, Süd positiv) in Pixel.

## Group Aktuelle Meldungen

Modul aktuelle Meldungen.

### Aktuelle Meldungen [/aktuelle-meldungen/meldungen]

#### GET

Der Webservice liefert aktuelle Meldungen im JSON-Format.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (AktuelleMeldungen)

    + Body

            {
                "anzahlMeldungen": 1,
                "redaktionelleMeldung": "Viel Spaß mit der neuen App wünscht Ihnen Ihre Straßenverkehrszentrale Baden-Württemberg!"
            }

#### Data Structures

##### AktuelleMeldungen

+ anzahlMeldungen: 2 (number, required) - Anzahl der Meldungen. Derzeit können nur 0, 1 oder 2 Meldungen vorliegen, die im folgenden beschrieben sind.
+ redaktionelleMeldung: Viel Spaß mit der neuen App wünscht Ihnen Ihre Straßenverkehrszentrale Baden-Württemberg! (string) - Optionaler Text der Meldung. Ist keine Meldung vorhanden, fehlt die Eigenschaft.
+ feinstaubalarm: true (boolean) - Optionales Flag ob Feinstaublalarm in Stuttgart veröffentlicht wurde. Liegt kein Feinstaubalarm vor, fehlt die Eigenschaft.

## Group Lkw-Parkplätze

Modul Lkw-Parkplätze.

### Liste aller Parkplätze [/lkw-parkplaetze/parkplaetze]

#### GET

Der Webservice liefert die Liste aller Lkw-Parkplätze nach Straße und Index (vom Nutzer definiert) sortiert im
JSON-Format. Die JSON-Datei enthält eine Liste der Parkplätze.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[LkwParkplatz], fixed-type)

#### Data Structures

##### LkwParkplatz

+ id: dlpa.a5.parkplatz.parkenBadBellingen (string, required) - Ein eindeutiger Schlüssel für den Parkplatz.
+ bezeichnung: Bad Bellingen (string, required) - Bezeichnung des Parkplatzes.
+ bereich: Freiburg (string, required) - Bereich in dem sich der Parkplatz befindet.
+ strasse: A5 (string, required) - Strasse an der der Parkplatz liegt.
+ fahrtrichtung: Basel (string, required) - Beschreibt die Fahrtrichtung, in die der Parkplatz an der Straße liegt.
+ betriebskilometer: 794 (number, required) - Nennt den Betriebskilometer an dem der Parkplatz an der Straße liegt.
+ anzahlStellplaetze: 62 (number, required) - Anzahl insgesamt vorhandener Lkw-Stellplätze.
+ art (enum, required) - Definiert die Art des Lkw-Parkplatz.
    + Parkplatz (string)
    + PWC (string)
    + TuR (string)
+ freieStellplaetze: 2 (number) - Optionale Anzahl freier Lkw-Stellplätze. Ist die Anzahl unbekannt, fehlt die Eigenschaft.
+ prognoseVollauslastung: 18:00 Uhr (string) - Optionaler Zeitpunkt der prognostizierten Vollauslastung der vorhandenen Lkw-Parkplätze. Existiert keine Prognose, fehlt die Eigenschaft.
+ lokation (Wgs84, required) - WGS-84-Koordinaten (lat, lon) der Lokation des Parkplatzes.

## Group Parken und Mitfahren

Modul Parken und Mitfahren.

### Liste aller Parkplätze [/parken-und-mitfahren/parkplaetze]

#### GET

Der Webservice liefert die Liste aller P+M-Parkplätze nach Straße und Index (vom Nutzer definiert) sortiert im
JSON-Format. Die JSON-Datei enthält eine Liste der Parkplätze.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[PumParkplatz], fixed-type)

#### Data Structures

##### PumParkplatz

+ id: PMA0301 (string, required) - Ein eindeutiger Schlüssel für den Parkplatz.
+ bezeichnung: Wertheim/<wbr>Lengfurt (string, required) - Bezeichnung des Parkplatzes.
+ bereich: Franken (string, required) - Bereich in dem sich der Parkplatz befindet.
+ strasse: A3 (string, required) - Strasse an der der Parkplatz liegt.
+ anzahlStellplaetze: 15 (number, required) - Anzahl insgesamt vorhandener Stellplätze.
+ anschlussbezeichnung: Wertheim/Lengfurt (string, required) - Bezeichnung des Anschlusses an der Straße, von dem man zum Parkplatz gelangt.
+ anschlussnummer: 66 (string) - Optionale Nummer des Anschlusses an der Straße, von dem man zum Parkplatz gelangt. Existiert keine Anschlussnummer für den Parkplatz, wird die Eigenschaft weggelassen.
+ zufahrt: über die L 231 zwischen Bettingen und Dertingen (string, required) - Beschreibung der Zufahrt vom Anschluss zum Parkplatz.
+ lokation (Wgs84, required) - WGS-84-Koordinaten (lat, lon) der Lokation des Parkplatzes.

## Group Reisezeiten

Modul Reisezeiten.

### Liste aller Reisezeiten [/reisezeiten/reisezeiten]

#### GET

Der Webservice liefert die Liste aller Reisezeiten nach ID sortiert im JSON-Format. Die JSON-Datei enthält eine Liste
der Reisezeiten.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[Reisezeit], fixed-type)

#### Data Structures

##### Reisezeit

+ id (number, required) - Ein eindeutiger Schlüssel für die Reisezeit.
+ strasse (string, required) - Strasse an der die Reisezeit liegt.
+ von (string, required) - Bezeichnung des Starts des Streckenabschnitts der Reisezeit.
+ bis (string, required) - Bezeichnung des Endes des Streckenabschnitts der Reisezeit.
+ aktuelleVerlustzeit (number) - Optionale aktuelle Verlustzeit auf dem Streckenabschnitt in Minuten. Ist die aktuelle Verlustzeit unbekannt, fehlt die Eigenschaft
+ winkel (number, required) - Winkel [0..359] zur Darstellung eines Richtungssymbols in der Karte.
+ kartendarstellung (object, required) - Optionen für die Darstellung der Reisezeit als Symbol in der Karte.
    + offset (Offset, required) - Verschiebung (x, y) des Reisezeitsymbols in der Karte relativ zu der Lokation der Reisezeit.
+ lokation (Wgs84, required) - WGS-84-Koordinaten (lat, lon) der Lokation der Reisezeit.

## Group Stauübersicht

Modul Stauübersicht.

### Liste aller Einträge der Stauübersicht [/stauuebersicht/stauuebersicht]

#### GET

Der Webservice liefert die Liste aller Einträge der Stauübersicht absteigend nach aktueller Gesamtwert und aufsteigend
nach Straße und Index (vom Nutzer definiert) sortiert im JSON-Format. Die JSON-Datei enthält eine Liste der Einträge der
Stauübersicht.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[Stauübersichteintrag], fixed-type)

#### Data Structures

##### Stauübersichteintrag

+ id: 17310427 (number, required) - Ein eindeutiger Schlüssel für den Eintrag der Stauübersicht.
+ strasse: B27 (string, required) - Strasse an der Eintrag der Stauübersicht liegt.
+ von: Tübingen (string, required) - Bezeichnung des Starts des Streckenabschnitts des Eintrags der Stauübersicht.
+ bis: Stuttgart (string, required) - Bezeichnung des Endes des Streckenabschnitts des Eintrags der Stauübersicht.
+ aktuellerGesamtwert: 0.136421 (number) - Optionaler aktueller Gesamtwert der Reisezeit. Ist der aktuelle Gesamtwert unbekannt, fehlt die Eigenschaft.
+ kartendarstellung (object, required) - Optionen für die Darstellung des Streckenabschnitts des Eintrags der Stauübersicht als Symbol in der Karte.
    + zoomstufe: 4 (number, required) - Zoomstufe mit dem die Karte geöffnet werden soll, wenn der Eintrag der Stauübersicht angezeigt wird.
+ reisezeit: +0 min (string) - Optionale aktuelle Verlustzeit auf dem Streckenabschnitt als Text. Gibt es keine aktuelle Verlustzeit für den Streckenabschnitt fehlt die Eigenschaft.
+ lokation (Wgs84, required) - WGS-84-Koordinaten (lat, lon) der Lokation des Eintrags.

## Group Straßenwetter

Modul Straßenwetter.

### Liste aller Wetterstationen [/strassenwetter/wetterstationen]

#### GET

Der Webservice liefert die Liste aller Wetterstationen nach Straße und Index (vom Nutzer definiert) sortiert im
JSON-Format. Die JSON-Datei enthält eine Liste der Wetterstationen und deren Messwerte.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[Wetterstation], fixed-type)

#### Data Structures

##### Wetterstation

+ id (string, required) - Ein eindeutiger Schlüssel für die Wetterstation.
+ bezeichnung (string, required) - Bezeichnung der Wetterstation.
+ bereich (string, required) - Bereich in dem sich die Wetterstation befindet.
+ strasse (string, required) - Strasse an der die Wetterstation liegt.
+ lufttemperatur (string, required) - Wert der Luftemperatur als Text.
+ fahrbahntemperatur (string, required) - Wert der Fahrbahntemperatur als Text.
+ niederschlag (string, required) - Zustand des Niederschlags als Text.
+ windgeschwindigkeit (string) - Optionaler Wert der Windgeschwindigkeit als Text. Hat die Wetterstation keinen Sensor für Windgeschwindigkeit, ist die Eigenschaft null.
+ windrichtung (string) - Optionaler Wert der Windrichtung als Text. Hat die Wetterstation keinen Sensor für Windrichtung, ist die Eigenschaft null.
+ symbolwind (boolean, required) - Flag ob eine Windwarnung veröffentlicht ist.
+ symbolniederschlag (string, nullable) - Optionale Art des Niederschlags. Muss einen der Werte SonneUndWolkeMitHinweisAufKeineDaten, SonneUndWolke, WolkeUndEinRegentropfen, WolkeUndEinigeRegentropfen, WolkeUndVieleRegentropfen, WolkeUndSchneeflocke, WolkeUndEinigeSchneeflocken, WolkeUndVieleSchneeflocken oder WolkeBlitzRegentropfen haben. Ist die Niederschlagsart unbekannt, ist die Eeigenschaft null.
+ lokation (Wgs84, required) - WGS-84-Koordinaten (lat, lon) der Lokation der Wetterstation.

## Group Verkehrskameras

Modul Verkehrskameras.

### Liste aller Kameras [/verkehrskameras/kameras]

#### GET

Der Webservice liefert die Liste aller Verkehrskameras Sortierung (vom Nutzer definiert) sortiert im JSON-Format. Die
JSON-Datei enthält eine Liste der Verkehrskameras.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[Verkehrskamera], fixed-type)

### Kamerabild einer Kamera [/verkehrskameras/kameras/{id}]

#### GET

Der Webservice liefert das aktuelle Bild der Kamera mit einer bestimmten ID.

+ Parameters
    + id: KA131 (string) - Der Schlüssel einer Kamera.
+ Response 200 (image/jpeg)
    + Header

            Content-Length: 77166

#### Data Structures

##### Verkehrskamera

+ id: KA131 (string, required) - Ein eindeutiger Schlüssel für die Kamera.
+ bezeichnung: AK Weinheim (string, required) - Bezeichnung der Kamera.
+ bereich: Rhein-Neckar (string, required) - Bereich in dem sich die Kamera befindet.
+ strasse: A5 (string, required) - Strasse an der die Kamera steht.
+ blickrichtung: Darmstadt (string, required) - Beschreibung der Blickrichtung der Kamera.
+ lokation (Wgs84, required) - WGS-84-Koordinaten (lat, lon) der Lokation der Kamera.
+ kartendarstellung (object, required) - Optionen für die Darstellung der Kamera als Symbol in der Karte.
    + offset (Offset, required) - Verschiebung (x, y) des Kamerasymbols in der Karte relativ zu der Lokation der Kamera.
    + winkel: 5 (number, required) - Winkel, um den die Kamera auf der Karte gedreht dargestellt wird. Der Winkel 0° steht für Ausrichtung nach Norden.
+ url: `https://api.svz-bw.de/verkehrskameras/kameras/KA131` (string, required) - URL zum Kamerabild.
+ relativeBlickrichtung (enum, required) - Relative Blickrichtung der Kamera auf der Straße.  -1 steht für Blickrichtung nach Norden oder Westen, 1 steht für Blickrichtung nach Süden oder Osten.
    + `-1` (number)
    + 1 (number)

## Group Verkehrsstörungen

Modul Verkehrsstörungen.

### Liste aller Störungen [/verkehrsstoerungen/stoerungen]

#### GET

Der Webservice liefert die Liste aller Verkehrsstörungen nach Straße und Zeitstempel sortiert im JSON-Format. Die
JSON-Datei enthält eine Liste der Störungen.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[Verkehrsstörung], fixed-type)

#### Data Structures

##### Verkehrsstörung

+ id: `rds.lms.{D  HE LMS-HE-85377}` (string, required) - Ein eindeutiger Schlüssel für die Störung.
+ titel: A5 Frankfurt Richtung Darmstadt (string, required) - Kurzbeschreibung der Störung.
+ beschreibung: <p>zwischen Langen/Mörfelden und Weiterstadt Bauarbeiten, vorübergehende Begrenzung der Breite auf 6,75 m, bis 31.08.2017 15:30 Uhr</p> (string, required) - Langbeschreibung der Störung.
+ strasse: A5 (string) - Strasse auf der die Störung vorliegt. Ist die Straße nicht bekannt, fehlt die Eigenschaft.
+ klasse: Verkehrsmeldung (enum, required) - Klasse der Störung.
    + Baustelle (string)
    + Betriebsmeldung (string)
    + Verkehrsmeldung (string)
+ art (enum) - Optionale Art der Störung definiert die Klasse näher. Eine Störung der Klasse Baustelle muss die Art Baustelle oder Nachtbaustelle haben. Eine Störung der Klasse Verkehrsmeldung muss die Art Baustelle, Sperrung, Staumeldung oder Warnmeldung haben. Für Störungen der Klasse Betriebsmeldung ist die Art nicht relevant und die Eigenschaft fehlt.
    + Baustelle
    + Nachtbaustelle
    + Sperrung
    + Staumeldung
    + Warnmeldung
+ quelle: `D  HE LMS-HE` (string) - Optionale Quelle der Störungsmeldung. Ist die Quelle nicht relevant, fehlt die Eigenschaft.
+ zeitstempel: `2017-05-24T13:30:00Z` (string, required) - Zeitstempel der Veröffentlichung der Störung.
+ lokation (Wgs84, required) - WGS-84-Koordinaten (lat, lon) der Lokation der Störung.

## Group Wechselwegweisung

Modul Wechselwegweisung.

### Liste aller dWiStas [/wechselwegweisung/dwistas]

#### GET

Der Webservice liefert die Liste aller dWiStas nach NBA-Index (vom Nutzer definiert) sortiert im JSON-Format. Die
JSON-Datei enthält eine Liste der dWiStas.

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[dWiSta], fixed-type)

### Bild der Anzeige eines dWiSta [/wechselwegweisung/dwistas/{id}]

#### GET

Der Webservice liefert das aktuelle Bild der Anzeige des dWiStas mit einer bestimmten ID.

+ Parameters
    + id: A5We (string) - Der Schlüssel eines dWiStas.
+ Response 200 (image/png)
    + Header

            Content-Length: 6965

#### Data Structures

##### dWiSta

+ id: A5We (string, required) - Ein eindeutiger Schlüssel für das dWiSta.
+ bereich: Wegweisung Rhein-Neckar (string, required) - Bereich in dem sich das dWiSta befindet.
+ strasse: A5 (string, required) - Strasse an der das dWiSta liegt.
+ von: AK Weinheim (string, required) - Bezeichnung des Starts des Streckenabschnitts für die Wechselwegweisung des dWiStas.
+ bis: Karlsruhe (string, required) - Bezeichnung des Endes des Streckenabschnitts für die Wechselwegweisung des dWiStas.
+ url: `https://api.svz-bw.de/wechselwegweisung/dwistas/A5We` (string, required) - URL zum Bild der aktuellen Anzeige des dWiStas.
+ lokation (Wgs84, required) - WGS-84-Koordinaten (lat, lon) der Lokation des dWiStas.
