=== Prüffall 1: Normalbetrieb Start/Stopp

==== Prüfobjekt

Start/Stopp wertet die Konfigurationsdateien korrekt aus und läuft im Normalbetrieb stabil.

==== Ausgangssituation

Für den Testfall werden die Skriptdateien [StartStopp1.1] und [StartStopp1.2] verwendet. 
Die Datei [StartStopp1.1] wird auf dem Rechner 1 in das Unterverzeichnis „startstopp“ innerhalb des Skript-Ordners kopiert 
und in "startstopp.json" umbenannt. Auf dem Rechner 2 wird mit der Datei [StartStopp1.2] entsprechend verfahren, wobei hier 
kein Unterverzeichnis verwendet wird.

Auf Rechner 1 wird Start/Stopp mit dem Aufrufparameter „-startStoppKonfiguration=startstopp“ gestartet, 
auf Rechner 2 wird Start/Stopp mit dem Aufrufparameter „-betriebsMeldungVersenden=nein“ gestartet. 

Auf beiden Rechnern wird beim Start die Bedienoberfläche mitgestartet.

==== Eingaben

* Die Skripte auf beiden Rechnern werden versioniert. Das erfolgt über das System-Menü der Bedienoberfläche im Editor-Modus.
  Eine Änderung der Skripte sollte nicht erforderlich sein. Als Nutzer für die Versionierung kann der Standard-Datenverteiler-
  Nutzer "Tester" mit dem bekannten geheimen Passwort verwendet werden.  
* Nach einer gewissen Zeit wird Start/Stopp auf Rechner 2 beendet. Das erfolgt über das Systemmenü der Bedienoberfläche im Online-Modus. 
* Wiederum nach einer kurzen Zeit wird Start/Stopp auf Rechner 2 per Shell-Skript neu gestartet.
* Die Bedienoberfläche auf Rechner 1 wird beendet und wieder gestartet. 
* Auf Rechner 2 wird Start/Stopp beendet, auf Rechner 1 der Datenverteiler und erst danach Start/Stopp. Zum Beenden das Datenverteilers
  kann optional per Systemmenü der Bedienoberfläche das Skript oder per Applikations-Menp die Inkarnation des Datenverteilers
  angehalten  werden.

==== Erwartete Ergebnisse

* Start/Stopp findet die Konfigurationsdateien in den angegebenen Verzeichnissen. Es erkennt beim ersten Start 
  jeweils die neue Konfigurationsdatei, das Skript wird nicht ausgeführt, weil es erst über die Bedienoberfläche
  versioniert werden muss.
* Beim zweiten Start ist keine Versionierung erforderlich, sondern das System startet einfach nur.
* Das definierte Kernsystem wird in der vorgegebenen Reihenfolge gestartet. Der Start kann über die Bedeinoberfläche
  verfolgt werden. Applikationen abseits des Kernsystems werden erst gestartet, wenn das Kernsystem komplett läuft
  und StartStopp eine Datenverteilerverbindung hergestellt hat. Abhängige Inkarnationen werden mit den angegebenen Wartezeiten 
  gestartet. 
* Die Applikationen Datenverteiler, Konfiguration, Parametrierung und Betriebsmeldungverwaltung werden direkt während
  des Startvorgangs gestartet. 
* Applikation02 wird zyklisch aller drei Minuten ausgeführt, wenn das Kernsystem bereit ist.
* Der Start und Stopp von Applikationen auf Rechner 1 werden über eine Betriebsmeldung publiziert (Zu Beobachten per GTM).
* Auf dem Rechner 2 werden für die Applikationszustände keine Betriebsmeldungen versendet.
* Start/Stopp kann ohne spezielle Berechtigungen gestartet werden und stellt keine Anforderungen an Betriebssystemvoraussetzungen. 
  Die Daten zur Versionierung werden in einem Verzeichnis unterhalb der verwendeten Konfiguration abgelegt. Die Betriebssystemumgebung 
  wird nicht geändert.
* Ausgaben der Applikationen auf Standardausgabe und Standardfehlerausgabe werden nur für die ersten 30 Sekunden nach dem Start
  einer Applikation gelesen, um Fehler vor der Initialisierung des Loggings zu erkennen. Die Ausgaben können potentiell in der 
  Oberfläche über das Applikations-Menü im Online-Modus betrachtet werden. 
* Die Zustände der Applikationen werden nicht farbig visualisiert.
