=== Prüffall 5: Fehlerbehandlung Konfiguration

==== Prüfobjekt

Start/Stopp erkennt Zyklen durch Start- und Stopp-Bedingungen. Start/Stopp erkennt, wenn es selbst in einer Konfiguration aufgerufen werden soll und wenn es bereits selbst läuft.

Der Prüffall deckt die Anforderungen Sys-StSt1 bis Sys-StSt-4, Sys-StSt-7 bis Sys-StSt9, Sys-StSt-11 bis Sys-StSt-13, Sys-StSt17 bis Sys-StSt21, Sys-StSt23 bis Sys-StSt-25, Sys-StSt-35, Sys-StSt-37 bis Sys-StSt-39, Sys-StSt-51, Sys-StSt-55 und Sys-StSt-67 teilweise oder vollständig ab.

==== Prüfvoraussetzungen

Auf dem Testrechner wurde das vorbereitete Datenverteiler-Testsystem installiert. Es liegt als ZIP-Archiv vor oder kann aus dem Zweig "testsystem" des SourceCode-Repositories entnommen werden.


==== Durchführung

===== Fall 5.1

Für den Testfall wird auf Rechner1 die Skriptdateien "startStopp05_1.json" verwendet. 
Die Datei "startStopp05_1.json" wird auf dem Rechner 1 in das Unterverzeichnis „startstopp“ innerhalb des Skript-Ordners kopiert und in "startstopp.json" umbenannt. 

Auf Rechner 1 werden die SWE StartStopp sowie die Bedienoberfläche per Shell-Skript gestartet.

Nach dem Start der SWE wird das StartStopp-Skript geladen und muss zunächst noch versioniert werden (siehe Prüffall 1).

Beim Versuch das Skript zu Versionieren wird eine Fehlermeldung angezeigt.

StartStopp wird wieder beendet.

===== Fall 5.2

Für den Testfall wird auf Rechner1 die Skriptdateien "startStopp05_2.json" verwendet. 
Die Datei "startStopp05_2.json" wird auf dem Rechner 1 in das Unterverzeichnis „startstopp“ innerhalb des Skript-Ordners kopiert und in "startstopp.json" umbenannt. 

Auf Rechner 1 werden die SWE StartStopp sowie die Bedienoberfläche per Shell-Skript gestartet.

Beim Versuch das Skript zu Versionieren wird eine Fehlermeldung angezeigt.

StartStopp wird wieder beendet.

===== Fall 5.3

Für den Testfall wird auf Rechner1 die Skriptdateien "startStopp05_3.json" verwendet. 
Die Datei "startStopp05_3.json" wird auf dem Rechner 1 in das Unterverzeichnis „startstopp“ innerhalb des Skript-Ordners kopiert und in "startstopp.json" umbenannt. 

Auf Rechner 1 werden die SWE StartStopp sowie die Bedienoberfläche per Shell-Skript gestartet.

Das Skript wird versioniert.

Die Applikation02 (StartStopp-SWE) wird gestoppt und zyklisch aller 3 Minuten neu gestartet. Im Log-File der Applikation ist eine Fehlermeldung, die die Ausführung verhindert hat zu finden.

StartStopp wird wieder beendet.


==== Erwartete Ergebnisse

* Start/Stopp erkennt die Zyklen in den Konfigurationen und bricht deren Start ab. Es wird eine Fehlermeldung in die Logdatei von Start/Stopp geschrieben.
* * Start/Stopp erkennt, dass es bereits läuft und startet nicht. Es wird eine Fehlermeldung in die Logdatei von Start/Stopp geschrieben.
