=== Prüffall 7: Verhalten bei Fehlern

==== Prüfobjekt

Für das Verhalten beim Auftreten von Fehlern beim Starten oder Stoppen von Applikationen sind verschiedene Optionen möglich.

==== Ausgangssituation

Auf Rechner 1 wird Start/Stopp mit dem Aufrufparameter „-startStoppKonfiguration=ststxml“ gestartet und der Bedienoberfläche gestartet. Der Benutzer „falscherBenutzer“ darf im System nicht vorhanden sein. Es wird eine Applikation benötigt, die intern mit mehreren Threads arbeitet. Dann wird die Applikation beendet, so dass ein interner Thread weiterläuft (Zombiethread). Die zu verwendende Konfigurationsdateien befinden sich in [StartStopp7.1], [StartStopp7.2], [StartStopp7.3], [StartStopp7.4], [StartStopp7.5], [StartStopp7.6] und [StartStopp7.7]. 
Die Dateien sind nacheinander in das Unterverzeichnis „ststxml“ zu kopieren und zu „startstopp.xml“ umzubenennen.

==== Eingaben

Das System wird mehrfach gestartet, anschließend wird es mehrfach gestartet und gestoppt.

==== Erwartete Ergebnisse

* Der Startvorgang wird abgebrochen, bereits gestartete Applikationen und Start/Stopp selbst werden beendet.
* Der Startvorgang wird abgebrochen, bereits gestartete Applikationen laufen weiter.
* Der Startvorgang wird fortgesetzt. Alle Applikationen außer der fehlerhaften laufen.
* Der Startvorgang wird fortgesetzt. Alle Applikationen außer der fehlerhaften laufen.
* Der Stoppvorgang wird abgebrochen. Die noch nicht gestoppten Applikationen laufen weiter.
* Der Stoppvorgang wird fortgesetzt. Alle Applikationen außer der fehlerhaften wurden beendet.
* Der Stoppvorgang wird fortgesetzt. Alle Applikationen außer der fehlerhaften wurden beendet.
