=== Prüffall 6: Fehlerbehandlung Applikationen

==== Prüfobjekt

Start/Stopp überwacht Applikationen und startet sie gegebenenfalls neu, wenn sie beendet wurden. Start/Stopp kann Probleme mit Applikationen, die sich in einem inkonsistenten Zustand befinden, beenden.

Der Prüffall deckt die Anforderungen Sys-StSt1 bis Sys-StSt5, Sys-StSt7 bis Sys-StSt9, Sys-StSt-12, Sys-StSt17 bis Sys-StSt21, Sys-StSt23 bis Sys-StSt-30, Sys-StSt-35, Sys-StSt-39, Sys-StSt-51, Sys-StSt-52, Sys-StSt-55, Sys-StSt-57, Sys-StSt-59, Sys-StSt-60 und Sys-StSt-66 teilweise oder vollständig ab.

==== Prüfvoraussetzungen

Auf dem Testrechner wurde das vorbereitete Datenverteiler-Testsystem installiert. Es liegt als ZIP-Archiv vor oder kann aus dem Zweig "testsystem" des SourceCode-Repositories entnommen werden.

Für den Testfall wird auf Rechner1 die Skriptdateien "startStopp06.json" verwendet. 
Die Datei "startStopp06.json" wird auf dem Rechner 1 in das Unterverzeichnis „startstopp“ innerhalb des Skript-Ordners kopiert und in "startstopp.json" umbenannt. 

Auf Rechner 1 werden die SWE StartStopp sowie die Bedienoberfläche per Shell-Skript gestartet.

==== Durchführung

Nach dem Start der SWE wird das StartStopp-Skript geladen und muss zunächst noch versioniert werden (siehe Prüffall 1).

Nach der Versionierung werden die Inkarnationen gestartet. 

Folgendes Verhalten wird beobachtet:

* Applikation02 beendet sich selbst, wird aber von StartStopp entsprechend der Konfiguration neu gestartet.
* Applikation03 beendet sich selbst, wird aber von StartStopp entsprechend der Konfiguration nicht neu gestartet.

Applikation05 beendet sich nicht, wenn die Datenverteilerverbindung geschlossen wird.

* Wenn Applikatio05 sich im Zustand INITIALISIERT befindet, wird sie über die Bedienoberfläche beendet. 
* Die Applikation verbleibt über einen längeren Zeitraum im Zustand STOPPEN_WARTEN, weil die Rückmeldung vom Betriebssystem nicht empfangen wurde
* Die Applikation wird erneut über die Bedienoberfläche beendet (ohne Datenverteilerschnittstelle, da die Datenverteilerverbindung beim ersten Versuch bereits geschlossen wurde).

==== Erwartete Ergebnisse

* Start/Stopp wird durch das Verhalten der Applikationen nicht negativ beeinflusst.
* Eine Applikation wird durch Start/Stopp neu gestartet, die andere nicht.
* Es ist möglich, die Applikation im inkonsistenten Zustand zu beenden und auch direkt neu zu starten.
