=== Prüffall 4: Fehlerbehandlung

==== Prüfobjekt

Start/Stopp kann mit auftretenden Fehlern umgehen, ohne dass Stabilität des Systems beeinträchtigt wird.

Der Prüffall deckt die Anforderungen Sys-StSt1 bis Sys-StSt5, Sys-StSt7 bis Sys-StSt12, Sys-StSt-14, Sys-StSt-15, Sys-StSt17 bis Sys-StSt21, Sys-StSt23 bis Sys-StSt-35, Sys-StSt-39 bis Sys-StSt-41, Sys-StSt-51, Sys-StSt-55, Sys-StSt-57, Sys-StSt-60, Sys-StSt-66 und Sys-StSt-67 teilweise oder vollständig ab.

==== Prüfvoraussetzungen

Auf dem Testrechner wurde das vorbereitete Datenverteiler-Testsystem installiert. Es liegt als ZIP-Archiv vor oder kann aus dem Zweig "testsystem" des SourceCode-Repositories entnommen werden.

Für den Testfall wird auf Rechner1 die Skriptdateien "startStopp04.json" verwendet. 
Die Datei "startStopp04.json" wird auf dem Rechner 1 in das Unterverzeichnis „startstopp“ innerhalb des Skript-Ordners kopiert und in "startstopp.json" umbenannt. 

Auf Rechner 1 werden die SWE StartStopp sowie die Bedienoberfläche per Shell-Skript gestartet.

==== Durchführung

Nach dem Start der SWE wird das StartStopp-Skript geladen und muss zunächst noch versioniert werden (siehe Prüffall 1).

Nach der Versionierung werden die Inkarnationen gestartet. 

Wenn das System gestartet ist werden folgende Operationen ausgeführt:

Folgende Punkte sind in der Oberfläche zu beobachten bzw. durchzuführen:

* Applikation04 wird automatisch gestoppt (Fehlerausgaben in der Log-Datei der Applikation)
* Applikation02 wird mit Fehler beendet, weil die Applikation nicht gefunden wurde
* Applikation05 wird manuell gestartet und automatisch gestoppt, weil ein unzulässiger Parameter an die JVM übergeben wurde.
* Eine Anwendung wird über das Betriebssystem beendet. Der Status wird visualisiert. 

==== Erwartete Ergebnisse

* Die Applikation mit dem falschen Benutzer (Applikation04) wird versucht, drei Mal zu starten. In der Log-Datei ist eine entsprechende Fehlermeldung zu finden. **Achtung:** Applikation04 wird in zwei Inkarnationen verwendet, d.h. im Debug-Verzeichnis existieren mehrere Log-Dateien!
* Der fehlgeschlagene Start der Anwendung mit zu wenig Speicher wird in der Logdatei von Start/Stopp vermerkt, ebenso die nicht vorhandene Anwendung. Diese Startfehler können über das Applikations-Menü mit dem Befehl "Ausgaben anzeigen" betrachtet werden (bevor StartStopp beendet wurde!)
* Der Stopp der von außen beendeten Anwendung wird in der Logdatei von Start/Stopp vermerkt, der Statuswechsel wurde in der Oberfläche angezeigt.
