=== Prüffall 10: Beendigung Start/Stopp

==== Prüfobjekt

Start/Stopp erkennt, wenn es von außen beendet wird.

Der Prüffall deckt die Anforderungen Sys-StSt-1 bis Sys-StSt-5, Sys-StSt-7 bis Sys-StSt-9, Sys-StSt-11, Sys-StSt-12, Sys-StSt17 bis Sys-StSt21, Sys-StSt23 bis Sys-StSt-35, Sys-StSt-39, Sys-StSt-40, Sys-StSt-44, Sys-StSt-45, Sys-StSt-53, Sys-StSt-55 bis Sys-StSt-57, Sys-StSt-59, Sys-StSt-66 und Sys-StSt-69 teilweise oder vollständig ab.

==== Prüfvoraussetzungen

Auf dem Testrechner wurde das vorbereitete Datenverteiler-Testsystem installiert. Es liegt als ZIP-Archiv vor oder kann aus dem Zweig "testsystem" des SourceCode-Repositories entnommen werden.

Für den Testfall wird auf Rechner1 die Skriptdateien [StartStopp10] verwendet. 
Die Datei [StartStopp108] wird auf dem Rechner 1 in das Unterverzeichnis „startstopp“ innerhalb des Skript-Ordners kopiert und in "startstopp.json" umbenannt. 

Auf Rechner 1 werden die SWE StartStopp sowie die Bedienoberfläche per Shell-Skript gestartet.

==== Durchführung

Nach dem Start der SWE wird das StartStopp-Skript geladen und muss zunächst noch versioniert werden (siehe Prüffall 1).

Nach der Versionierung werden die Inkarnationen gestartet. 

* Die Applikation04 wird manuell gestartet. 
* Start/Stopp wird über das Betriebssystem beendet. 
* Start/Stopp und die manuelle Applikation werden erneut gestartet.
* StartStopp wird per Telegramm über die Bedienoberfläche beendet.

==== Erwartete Ergebnisse

* In beiden Fällen wird das Gesamtsystem sicher und korrekt heruntergefahren und beendet.
* Start/Stopp signalisiert auch bei länger dauernden Prozessen, dass es noch läuft, der aktuelle Status beim Beenden der Applikationen wird signalisiert.
