== Prozessverwaltung

Die Prozessverwaltung liest das von der Skriptverwaltung bereitgestellte
StartStopp-Skript. Wenn ein gültiges Skript zur Verfügung steht, werden für die
definierten Inkarnationen Applikationen erzeugt und entsprechend den
Abhängigkeiten und den Regeln ausgeführt.

Die Applikationen werden als individuelle Threads ausgeführt und passen ihren
Status entsprechend den Bedingungen und den Rückmeldungen aus dem Betriebssystem
an.

Folgende Statuswerte sind für eine Applikation vorgesehen:

* _INSTALLIERT_: ist der initiale Status des Applikationsobjekts
* _KERNSYSTEM_: die Applikation kann nicht gestartet werden, weil das
  Kernsystem noch nicht aktiv ist
* _STARTBEDINGUNG_: die Applikation soll gestartet werden, die Ausführung wird
   aber durch die Startbedingung verhindert
* _STARTVERZOEGERUNG_: die Startbedingung für die Applikation ist erfüllt, es
  ist aber eine Wartezeit bis zum Start definiert
* _STARTEN_: der Start der Applikation wurde initialisiert, es ist jedoch noch
  kein Betriebssystemprozess aktiv
* _GESTARTET_: die Applikation wurde als Betriebssystemprozess gestartet,
  es wurde jedoch noch keine Initialisierungsmeldung über den Datenverteiler geliefert.
* _INITIALISIERT_: die Applikation ist aktiv und hat über den Datenverteiler eine
  Initialisierungsmeldung geliefert
* _STOPPBEDINGUNG_: die Applikation soll gestoppt werden, die Ausführung wird
     aber durch die Stopbedingung verhindert
* _STOPPVERZOEGERUNG_: die Stoppbedingung für die Applikation ist erfüllt, es
       ist aber eine Wartezeit bis zum Stopp definiert
* _STOPPEN_: die Applikation wird gestoppt, der Betriebssystemprozess ist aber
  noch aktiv
* _GESTOPPT_: die Applikation wurde definiert beendet
* _ABGEBROCHEN_: die Applikation wurde beendet, weil der Start fehlgeschlagen ist
  und die Anzahl der Wiederholungen überschritten wurde

[plantuml, "applikations_status"]
----
title Zustandsdiagramm für Applikationen in StartStopp \n

[*] --> INSTALLIERT
INSTALLIERT ---> KERNSYSTEM: (1)
INSTALLIERT ---> STARTBEDINGUNG: (2)
INSTALLIERT ---> STARTEN: (3, 15)

KERNSYSTEM ---> STARTBEDINGUNG: (4)
KERNSYSTEM ---> STARTEN: (3, 15)
KERNSYSTEM ---> GESTOPPT: (5, 16)

STARTBEDINGUNG ---> STARTVERZOEGERUNG: (10)
STARTBEDINGUNG ---> STARTEN: (15)
STARTBEDINGUNG ---> GESTOPPT: (5, 16)

STARTVERZOEGERUNG ---> STARTBEDINGUNG: (11)
STARTVERZOEGERUNG ---> STARTEN: (3, 15)
STARTVERZOEGERUNG ---> GESTOPPT: (5, 16)

STARTEN ---> GESTARTET: (6)
STARTEN ---> INITIALISIERT: (7)
STARTEN ---> ABGEBROCHEN: (8)

GESTARTET ---> GESTOPPT: (9, 16)
GESTARTET ---> STOPPBEDINGUNG: (2)
GESTARTET ---> STOPPVERZOEGERUNG: (10)
GESTARTET ---> STOPPEN: (12)
GESTARTET ---> INITIALISIERT: (13)

INITIALISIERT ---> GESTOPPT: (9, 16)
INITIALISIERT ---> STOPPBEDINGUNG: (2)
INITIALISIERT ---> STOPPVERZOEGERUNG: (10)
INITIALISIERT ---> STOPPEN: (12)

STOPPBEDINGUNG ---> STOPPVERZOEGERUNG: (10)
STOPPBEDINGUNG ---> STOPPEN: (12)
STOPPBEDINGUNG ---> GESTOPPT: (14, 16)

STOPPVERZOEGERUNG ---> STOPPBEDINGUNG: (11)
STOPPVERZOEGERUNG ---> STOPPEN: (12)
STOPPVERZOEGERUNG ---> GESTOPPT: (14, 16)

STOPPEN ---> GESTOPPT: (14)

GESTOPPT ---> STARTEN: (15)

ABGEBROCHEN ---> STARTEN: (15)

note as N1
  1: Kernsystem ist noch nicht bereit
  2: Bedingung ist nicht erfüllt
  3: Applikation kann gestartet werden
  4: Startbedingung nicht erfüllt
  5: Applikation wurde über die Schnittstelle beendet
  6: Betriebssystemprozess wurde gestartet
  7: Betriebssystemprozess wurde gestartet
     und es wird keine Initialisierung erwartet
  8: Fehler beim Starten des Prozesses
  9: Betriebssystemprozess wurde ohne StartStopp beendet
  10: Bedingung ist erfüllt, Verzögerung ist definiert
  11: Verzögerungszeit beendet, Bedingung nicht mehr gültig
  12: Betriebssystemprozess soll gestoppt werden
  13: Initialisierungsmeldung vom Datenverteiler empfangen
  14: Applikation wurde beendet
  15: Applikation wird händisch gestartet, Startbedingungen werden ignoriert
  16: Applikation wird händisch gestoppt, Stoppbedingungen werden ignoriert
end note

----

[plantuml, "applikations_status_2"]
----
title Alternatives Zustandsdiagramm für Applikationen in StartStopp \n

[*] --> INSTALLIERT
INSTALLIERT ---> STARTENWARTEN: Manueller oder automatischer Start
STARTENWARTEN ---> GESTARTET: Startbedingungen erfüllt
GESTARTET ---> GESTOPPT: Fehler beim Starten
GESTARTET ---> STOPPENWARTEN: Stopp angefordert
GESTARTET --> INITIALISIERT: Rückmeldung vom DAV
STOPPENWARTEN  ---> GESTOPPT: Stoppbedingungen erfüllt, Systemprozeß beendet
STARTENWARTEN ---> GESTOPPT: Stopp angefordert
INITIALISIERT --> STOPPENWARTEN: Stopp angefordert

note left of STOPPENWARTEN
    Kann per Request übersprungen werden
end note

note right of STARTENWARTEN
    Kann per Request übersprungen werden
end note

----
