= Anwenderforderungen Sys Start/Stopp
Version: 9.0
Stand: 13.03.17
:toc: left
:doctype: book
:encoding: utf-8
:toclevel: 4
:sectnums:

[dedication]
Quellenverweis
=============

Das Dokument basiert auf einem Anforderung des NERZ e.V.
und wurde zur Anpassung in dieses Format überführt.

Name der Originaldatei: AFo_Sys-StartStopp_FREI_V9.0_D2017-03-13.docx
Verfügbar beim http://www.nerz-ev.de[NERZ]

== Allgemeines
=== Lizenz
Dieses Dokument steht unter der Creative-Commons-Lizenz Namensnennung - Weitergabe unter
gleichen Bedingungen 4.0 International. Um eine Kopie dieser Lizenz zu sehen, besuchen Sie
http://creativecommons.org/licenses/by-sa/4.0/[].

=== Änderungsübersicht

.Dokumentenverteiler
[cols="5*", options="header"]
|===
| Version
| Datum
| Kapitel
| Bemerkungen
| Bearbeiter

| 6.1
| 15.03.2015
|
| alle Umstellung der Gesamt-AFo auf Einzel-AFo
| H. C. Kniß (HCK), FTB NERZ

| 6.2
| 26.01.2016
|
| alle Anpassungen entsprechend den Ergebnissen des Zertifizierungszwischenberichts
| H. C. Kniß (HCK), FTB NERZ

| 6.3
| 15.03.2016
|
| alle Schlussredaktion
| H. C. Kniß (HCK), FTB NERZ

| 7.0
| 31.03.2016
|
| Überführung in den Zustand akzeptiert
| H. C. Kniß (HCK), FTB NERZ

| 8.0
| 30.08.2016
|
| Alle Komplettüberarbeitung
| T. Bräuner

| 9.0
| 04.10.2016
| 6.6.1
| Einarbeitung Anmerkungen NERZ, Überführung in den Zustand „Akzeptiert“
| T. Bräuner

|
| 13.03.2017
|
| Schlussfertigung Ausschreibung
| T. Bräuner

|===

=== Abkürzungsverzeichnis

Siehe [AbkBSVRZ].

Darüber hinaus werden folgende Abkürzungen verwendet:

|=======
| BASt  | Bundesanstalt für Straßenwesen             |
| BSVRZ | Basis System VRZ                           |
| ERZ   | Einheitliche Rechnerzentralensoftware      |
| NERZ  | Nutzer der ERZ, siehe auch www.nerz-ev.de  |
|=======

=== Definitionen

Siehe [GlossarBSVRZ].
Darüber hinaus werden folgende Definitionen verwendet:
--- ---

=== Referenzierte Dokumente / URLs

Die folgende Tabelle listet die im Dokument verwendeten Referenzen auf. Zum aktuellen Zeitpunkt sind die folgenden Archiv-URLs vorhanden:
NERZ-Archiv: http://www.nerz-ev.de/ -> Dokumente und Software

[cols="2*", options="autowidth"]
|=======
| [VMOD97] 
| Der Bundesminister des Inneren, Entwicklungsstandard für ITSysteme des Bundes Vorgehensmodell, Juni 1997, KBSt,
  Koordinations- und Beratungsstelle der Bundesregierung für
  Informationstechnik in der Bundesverwaltung.

| [AbkBSVRZ] 
| Abkürzungsverzeichnis BSVRZ Gesamt
  NERZ-Archiv: Abk_BSVRZ-Gesamt_FREI_V4.0_D2006-08-15.doc

| [GlossarBSVRZ] 
| Glossar BSVRZ Gesamt
  NERZ-Archiv: SE-02.0002-Glos-0.4__Glossar__global__.pdf

| [AFoBSVRZGesamt] 
| Anwenderforderungen des BSVRZ, ursprüngliche Gesamtfassung
  NERZ-Archiv: AFo_BSVRZ-Gesamt_FREI_V6.0_D2009-11-03.doc

| [SysArcBSVRZ] 
| Systemarchitektur des BSVRZ
  NERZ-Archiv: SysArc_BSVRZ-Gesamt_FREI_V6.0_D2009-11-19.doc

| [AFoERZGlobal] 
| Übergeordnete Anwenderforderungen zur ERZ
  NERZ-Archiv: AFo_ERZ-Global_FREI_V7.0_D2016-03-31.doc

|=======

== Zweck des Dokuments

Das vorliegende Dokument beschreibt die Anforderungen an die Funktionseinheit zum Starten,
Stoppen und Überwachen der Prozesse des Systems.

== Ist-Aufnahme und Ist-Analyse

Siehe [AFoERZGlobal]

== IT-Sicherheitsziel

****
*GLO-1, IT-S-1 und IT-S-2* IT-Sicherheitsziel
****

Die Anwenderforderung *GLO-1* (Systemverfügbarkeit), *IT-S-1* (Kommunikation getrennter
Systemkomponenten) und *IT-S-2* (Zugriff auf Systemteile) aus dem Dokument [AFoERZGlobal] gilt für die in diesem Dokument beschriebenen Funktionen und ist entsprechend umzusetzen.

== Bedrohungs- und Risikoanalyse

****
*IT-S-3 bis ITS-8* Bedrohung und Risiko
****

Die Anforderungen *IT-S-3* bis *IT-S-8* aus dem Dokument [AFoERZGlobal] gelten auch für die in
diesem Dokument beschriebenen Funktionen.

== IT-Sicherheit

****
*GLO-2* und *IT-S-7* IT-Sicherheit
****

Die Anwenderforderung *GLO-2* (Zugriffschutz) und *IT-S-7* (Unberechtigter Zugriff auf
Komponenten) aus dem Dokument [AFoERZGlobal] gilt für die in diesem Dokument beschriebenen
Funktionen und ist entsprechend umzusetzen

== Fachliche Anforderungen

=== Grobe Systembeschreibung

Der koordinierte Start/Stopp von Applikationen bzw. Prozessen mit den jeweiligen
Aufrufparametern etc. ist durch eine Applikation zu realisieren.
Die zum Starten bzw. Stoppen benötigten Informationen sind in einer zentralen
plattformunabhängigen editierbaren Konfigurationsdatei zu sichern, die von der Start/Stopp-
Applikation in der Initialisierungsphase ausgewertet wird. Dies sind beispielsweise die

* Namen
* Aufrufparameter Java
* Aufrufparameter Applikation
* Startreihenfolge
* Stoppreihenfolge
* Startverhalten

der zu verwaltenden Applikationen. Die Start-/Stopp-Funktion liest diese Informationen aus und startet/stoppt entsprechend den Vorgaben die „übrigen“ Systemteile. Damit ist diese Applikation i. d. R. als erste zu starten, da sie für den Start der übrigen SW-Einheiten einer bzw. mehrerer zugeordneter HW-Einheiten (Rechner) zuständig ist.
Die spezifischen Anwenderforderungen sind in Kap. 6.6 enthalten.

=== Organisatorische Einbettung

Siehe [AFoERZGlobal]

=== Nutzung

Siehe [AFoERZGlobal]

=== Kritikalität des Systems

Entsprechend den Festlegungen zur Kritikalität in [AFoERZGlobal] wird die Kritikalität für die in
diesem Dokument beschriebene Funktionalität als
- mittel
eingestuft

=== Externe Schnittstellen

==== Mensch-Maschine-Schnittstelle

****
*BuV-1,BuV-2,BuV-4,BuV-6,BuV-12* Allgemeine Anforderungen Bedienung
****

Das spezifizierte Teilsystem ist ein Serversystem bzw. Serverprozess. Es verfügt über eine
Schnittstelle zum Anwender, über die der Start-/Stopp-Vorgang parametriert und gesteuert werden
kann. Die grundsätzlichen Anforderungen BuV-1 (Zugangsschutz) (teilweise), BuV-2
(Bedienerfreundlichkeit), BuV-4 (Fehlermeldungen), BuV-6 (Fenster) und BuV-12 (Dialoge) aus
[AFoERZGlobal] gelten auch für diese Schnittstelle. Die detaillierten Anforderungen an diese
Schnittstelle sind in Kapitel 6.6.2 beschrieben.

==== Externe Kommunikation

Die geforderten Funktionen haben keine externen Schnittstellen im Sinne der [SysArcBSVRZ] 

NOTE: Die Aufteilung der ursprünglichen Anwenderforderungen [AFoBSVRZGesamt] in
      einzelne (Teil-) Anwenderforderungen erfolgte im Rahmen der Zertifizierung der ERZ-Software, um eine gewährleisten. 
      Zu diesem Zeitpunkt war die Systemarchitektur bereits vorhanden, die Aufteilung der ursprünglichen AFo-Gesamtfassung 
      erfolgte entsprechend der Systemarchitektur. Aus diesem Grund wird hier auf die [SysArcBSVRZ] verwiesen,
      da sowohl im Rahmen der AFo-Aufteilung als auch für zukünftige Erweiterungen des Systems die dort 
      festgelegte Systemarchitektur vorgeben ist.

=== Beschreibung der Funktionalität

==== Funktionale Anforderungen an Start/Stopp von Applikationen

****
*Sys-5* Start- und Stopp von Applikationen
****

*Der koordinierte Start/Stopp von Applikationen bzw. Prozessen mit den jeweiligen Aufrufparametern ist durch eine Applikation zu realisieren.*

****
*Sys-StSt-1* Zentrale Konfigurationsdatei
****
*Die zum Starten bzw. Stoppen benötigten Informationen sind in einer zentralen plattformunabhängigen editierbaren Konfigurationsdatei zu sichern*,
die von der Start/Stopp-Applikation in der Initialisierungsphase ausgewertet wird. *Die Informationen für das Starten und Stoppen von Applikationen 
werden je Rechner in einer xml-Datei „startstopp.xml“ gespeichert.* Für jede Applikation wird dort ein Datensatz angelegt, der die Informationen
beschreibt. *Durch die Verwendung eines geeigneten Zeichensatzes (z. B. UTF-8) ist sicher zu stellen, dass Start/Stopp unabhängig vom eingesetzten Betriebssystem, auch über
Rechnergrenzen hinweg, arbeitet.*

****
*Sys-StSt-2* Aufrufparameter
****
Die Applikation muss den Aufrufparameter „-startStoppKonfiguration“ auswerten. Hier wird
das Verzeichnis angegeben, in dem die zu verwendende xml-Datei liegt. Wenn der Parameter
nicht angegeben wird, ist als Standardwert „.“ zu versorgen, das heißt die Datei liegt im gleichen
Verzeichnis. Außerdem muss die Applikation den Aufrufparameter
„-betriebsMeldungVersenden“ auswerten. Hierüber wird gesteuert, ob die Applikation
Betriebsmeldungen versendet oder nicht. Wenn der Parameter nicht angegeben wird, ist als
Standardwert „ja“ zu versorgen, das heißt, Betriebsmeldungen werden versendet.

****
*Sys-StSt-3* Aufbau und Inhalt der xml-Datei
****
Die xml-Datei besteht aus einem globalen und einem applikationsspezifischen Abschnitt.
Der Aufbau ist in einer DTD beschrieben. Der globale Abschnitt der xml-Datei enthält die
Informationen, die für alle Applikationen gelten:

****
*Sys-StSt-4* Definition Kernsystem
****
* Definition eines Kernsystems, welches laufen muss, bevor alle anderen Applikationen gestartet werden: Die Namen der zum Kernsystem gehörigen Applikationen werden in der Reihenfolge aufgeführt, in der sie gestartet werden müssen; evtl. definierte Start- bzw. Stoppabhängigkeiten werden ignoriert. Die Angabe eines Kernsystems ist optional.

****
*Sys-StSt-5* Makros Aufrufparameter
****

* Makros für Aufrufparameter. Diese Zeichenketten können in der Definition der Aufrufparameter im applikationsspezifischen Teil verwendet werden. Üblicherweise wird man hiermit Parameter zusammenfassen, die bei mehreren Applikationen benutzt werden. Ein Makro erhält einen Namen und einen Wert (= beliebige Zeichenkette). Bereits definierte Makros können ebenfalls verwendet werden. Zur Verwendung des Makros ist dessen Name eingebettet in %...% einzutragen.

****
*Sys-StSt-6* Liste Rechner
****

* Liste der referenzierten Rechner. Jeder Rechner ist durch einen Namen und seine TCPAdresse
beschrieben. Werden keine Rechner definiert, so können nur Abhängigkeiten zu
Applikationen auf dem lokalen Rechner beschrieben werden.

****
*Sys-StSt-7* Definition Protokolldateien
****

* Definition von Protokolldateien für die Standard- und die Standardfehlerausgabe. Der
Name der Datei und eine maximale Größe (n MBytes) muss spezifiziert werden. Der „Logging“-
Mechanismus des Systems ist zu nutzen.

Der applikationsspezifische Abschnitt enthält die Informationen für die einzelnen zu
startenden bzw. zu stoppenden Applikationen:

****
*Sys-StSt-8* Inkarnationsname
****

* Inkarnationsname über den der Datensatz referenziert werden kann (optional). Wird dieser
Name nicht definiert, so kann auf die zugehörige Inkarnation nicht Bezug genommen werden.

****
*Sys-StSt-9* Name. Pfad der Klasse
****

* Name der Main-Klasse und Pfad der auszuführenden Applikation (Pflicht).

****
*Sys-StSt-10* Aufrufparameter der Inkarnation
****

* Aufrufparameter der Inkarnation (optional). Dazu können die im globalen Abschnitt
definierten Makros verwendet werden. Aufrufparameter und Makros werden in der Reihenfolge
an die Applikation weitergegeben, wie sie in der xml-Datei aufgeführt sind. Eine Applikation
kann auch ohne Aufrufparameter gestartet werden. Makros werden hier über ihren Namen
referenziert. Spezifische Aufrufparameter werden durch eine Zeichenkette definiert, die an die
Applikation weitergegeben wird. Ein Aufrufparameter wird also als <aufrufparameter wert
= “-name=wert“/> definiert. Die Aufrufparameter einer Applikation können aber auch in einer
Zeichenkette definiert werden.

****
*Sys-StSt-11* Startart
****

* Startart (optional):
** „automatisch“ (Standardoption) steht für Applikationen, die durch Start/Stopp direkt bei
    Ausführung gestartet werden.
** „manuell“ steht für Applikationen, die zu einem beliebigen Zeitpunkt manuell über die
    Nutzerschnittstelle von Start/Stopp gestartet werden können. Sie werden Start/Stopp über
    den Eintrag lediglich bekanntgemacht.
** „intervall“ steht für Applikationen, die zu einem bestimmten, angegebenen Zeitpunkt
    gestartet werden. Die Spezifikation des Zeitpunkts erfolgt in cron-Syntax.
**  Die beiden Optionen „automatisch“ und „intervall“ können jeweils noch durch die Angabe
    ergänzt werden, ob Start/Stopp die Applikation nach ihrer Beendigung (z. B. bei Absturz der
    Applikation) automatisch wieder neu starten soll oder nicht (neustart=“ja“ bzw.
    neustart=“nein“). Standard ist hierbei neustart=“ja“.

****
*Sys-StSt-12* Startbedingungen
****

* Startbedingungen (optional). Dies ist eine optionale Liste von Inkarnationen, die bereits
  gestartet sein müssen, bevor die Applikation gestartet werden darf. Wird eine Inkarnation auf
  einem anderen Rechner referenziert, so muss der Rechnername angegeben werden. Weiter ist
  anzugeben, ob lediglich auf den Start der Applikation (Standard) oder auch auf den Abschluss
  derer Initialisierung zu warten ist. Optional kann eine Wartezeit in Sekunden angegeben
  werden, die seit dem Start der angegebenen Inkarnation verstrichen sein muss.

****
*Sys-StSt-13* Stoppbedingungen
****

* Stoppbedingungen (optional). Analog zu den Startbedingungen wird hier eine optionale Liste
  definiert, die die Inkarnationen enthält, die beendet sein müssen, bevor die aktuelle Applikation
  beendet werden kann. Wird eine Inkarnation auf einem anderen Rechner referenziert, so muss
  der Rechnername angegeben werden. Auch hier gibt es eine optionale Wartezeit, die zwischen
  dem Beenden der aktuellen Applikation und dem Beenden der referenzierten Inkarnationen
  verstreichen muss.

****
*Sys-StSt-14* Startverhalten bei Fehlern
****

* Startverhalten bei Fehlern (optional). Hier wird festgelegt, wie sich Start/Stopp beim Auftreten
  eines Fehlers beim Startversuch verhält:
** Gesamten Start-Vorgang abbrechen und alle bereits gestarteten Applikationen (incl.
  Start/Stopp) beenden.
** Gesamten Start-Vorgang abbrechen, aber alle bereits gestarteten Applikationen laufen
  lassen.
** Problem ignorieren und nächste Applikation starten (Standardverhalten).
** Außerdem kann angegeben werden, wie oft der Startversuch wiederholt wird, bevor das
  zuvor definierte Fehlerverhalten ausgeführt wird (Standard: nullmaliges Wiederholen).

****
*Sys-StSt-15* Stoppverhalten bei Fehlern
****

* Stoppverhalten bei Fehlern (optional). Hier wird festgelegt, wie sich Start/Stopp beim
  Auftreten eines Fehlers beim Stoppversuch verhält:
** Gesamten Stopp-Vorgang abbrechen.
** Stopp der Applikation erzwingen.
** Problem ignorieren und nächste Applikation stoppen. (Standardverhalten).
** Außerdem kann angegeben werden, wie oft der Stoppversuch wiederholt wird, bevor das
  zuvor definierte Fehlerverhalten ausgeführt wird (Standard: nullmaliges Wiederholen).

****
*Sys-StSt-16* Mehrere Inkarnationen
****

Wenn von einer Applikation mehrere Inkarnationen gestartet werden sollen, ist für jede
Inkarnation ein eigener Datensatz in der xml-Datei anzulegen.

****
*Sys-StSt-17* Pfadangaben in URL-Form
****

Alle Pfadangaben in der xml-Datei müssen in URL-Form aufgeführt werden. Die Applikation
hat für die plattformunabhängige Interpretation zu sorgen.

****
*Sys-StSt-18* Keine speziellen Berechtigungen
****

Die Start-/Stopp-Applikation muss ohne spezielle Berechtigungen (wie Administratorenrechte)
betrieben werden können.

****
*Sys-StSt-19* Datenablage
****

Die Daten, die die Applikation speichern muss, müssen in einem sicherheitstechnisch
unkritischen Bereich abgelegt werden (z. B. Userspace). Die Schreibrechte müssen auf den
verwendeten Benutzer eingeschränkt sein.

****
*Sys-StSt-20* Betriebssystemunabhängigkeit
****

Die Start-/Stopp-Applikation darf die Betriebssystemumgebung nicht ändern. Beispielsweise
dürfen keine Umgebungsvariablen geändert werden. Die Betriebssystemunabhängigkeit ist
durch andere Mechanismen sicher zu stellen.

****
*Sys-StSt-21* Umlenkung von Ausgaben
****

Die Start-/Stopp-Applikation darf die Standardausgabe und die Standardfehlerausgabe der
verwalteten Applikationen nicht umlenken. Da die Umlenkung dieser Ausgaben die Systeme
stark belastet, wird die normale „Logging“-Funktionalität der verwalteten Applikationen als
ausreichend angesehen.

****
*Sys-StSt-22 (TSys-4)* Versionierung der Konfiguration
****

Die Start-/Stopp-Konfiguration darf nur überwacht durch die Applikation geändert werden.
Änderungen an der Konfiguration müssen vor deren Aktivierung im System nachvollziehbar
gespeichert werden. Es muss nachvollzogen werden können, wer welche Änderung wann warum
durchgeführt hat. Hierzu ist die Start-/Stopp-Konfiguration zu versionieren.

Die Versionierungsinformationen zur Start-/Stopp-Konfiguration müssen auf jedem Rechner
in einer speziellen xml-Datei „startstoppversionierung.xml“ gespeichert werden. Dort sind für
jede Änderung die Informationen zu:

* Versionsnummer, beginnend mit eins bei der erstmaligen Erstellung einer Konfiguration.
* Änderungsdatum (bzw. Erstellungsdatum) der Konfiguration
* Urheber der Änderung
* Grund der Änderung
* Prüfsumme der Konfiguration

zu speichern. Der Aufbau der xml-Datei ist in einer DTD beschrieben.

****
*Sys-StSt-23* Zwei Arten der Konfigurationsänderung
****

Die Änderung der Start-/Stopp-Konfiguration kann auf zwei Arten durchgeführt werden, die
beide bei der Versionierung berücksichtigt werden müssen:

* Online-Änderung: Die Änderungen an der Konfiguration erfolgen im laufenden Betrieb von
Start/Stopp. Wenn diese Änderungen gespeichert werden und bevor die Änderungen aktiviert
werden können, muss automatisch eine neue Version angelegt werden. Dabei müssen die
benötigten Informationen vom Anwender angegeben werden. Erst danach kann die neue
Konfiguration verwendet werden.
* Offline-Änderung: Wenn die Änderungen an der xml-Datei mit einem externen Editor
durchgeführt werden, muss dies beim Start der Applikation (unter Verwendung der Prüfsumme)
erkannt und der Anwender darauf hingewiesen werden. Wenn das vom Anwender bestätigt
wird, muss eine neue Version der Konfiguration angelegt werden, wobei die notwendigen
Informationen wiederum vom Anwender angegeben werden müssen. Danach wird die neue
Version direkt zum Starten des Systems verwendet.

****
*Sys-StSt-24 (Sys-6,TSys-5)* Startvorgang
****

Das Starten des Systems geschieht in folgenden Schritten, automatisch nach Start der
Applikation:

****
*Sys-StSt-25* Starten der Applikation
****

* Starten der Applikation, sofern nicht bereits eine Applikation mit dem gleichen Klassennamen
läuft. Ansonsten wird der Startvorgang mit einer Fehlermeldung auf die Standardfehlerausgabe
abgebrochen.

****
*Sys-StSt-26* Überprüfung
****

* Überprüfung der Versionsnummer und der Prüfsumme. Wenn diese Werte nicht mit den
erwarteten übereinstimmen, wird der Anwender mit einer Meldung darauf hingewiesen. Der
Anwender kann dann den Start abbrechen oder die geänderte Konfiguration versionieren.

****
*Sys-StSt-27* Starten Kernsystem
****

* Starten des definierten Kernsystems unter Berücksichtigung der definierten
Startbedingungen. Start/Stopp erzeugt zu jeder Applikation eine über alle Rechner, mit deren
Start/Stopp-Applikationen es verbunden ist, eindeutige ID, über die die Applikationen
verwechslungsfrei adressiert werden können.

****
*Sys-StSt-28* Abgleich mit anderen Rechnern
****

* Abgleich mit Start-/Stopp-Applikationen auf referenzierten Rechnern, bis deren
Kernsysteme gestartet sind. Der Start der nicht zum Kernsystem gehörigen Applikationen wird
erst dann durchgeführt, wenn die Kernsysteme auf den referenzierten Rechnern erfolgreich
gestartet wurden. Hier wird auch den Start/Stopp-Applikationen auf den anderen Rechnern
mitgeteilt, welche dortigen Applikationen Startvoraussetzung für den Start anderer Applikationen
darstellen.

****
*Sys-StSt-29* Starten restliche Applikationen
****

* Starten der restlichen Applikationen unter Berücksichtigung der definierten
Startbedingungen. Die Kommunikation mit den Start/Stopp-Applikationen der anderen Rechner
wird aufrechterhalten: Zum einen wird diesen mitgeteilt, wann eine Applikation gestartet wurde,
die Startvoraussetzung für eine Applikation auf einem anderen Rechner darstellt, andererseits
werden solche Telegramme von anderen Rechnern empfangen. Auch hier erzeugt Start/Stopp
zu jeder Applikation eine über alle Rechner, mit deren Start/Stopp-Applikationen es verbunden
ist, eindeutige ID, über die die Applikationen verwechslungsfrei adressiert werden können.

****
*Sys-StSt-30* Abschließender Informationsaustausch
****

* Abschließender Informationsaustausch mit anderen Start-/Stopp-Applikationen über
gestartete Applikationen.

****
*Sys-StSt-31 (TSys-6)* Stoppvorgang
****

Das Stoppen des Systems geschieht in folgenden Schritten:

****
*Sys-StSt-32* Einleitung Stoppvorgang
****

* Versenden eines Telegramms und einer Betriebsmeldung, dass der Stoppvorgang eingeleitet wird.

****
*Sys-StSt-33* Stoppen Applikationen
****

* Stoppen aller Applikationen, die nicht zum Kernsystem gehören, unter Berücksichtigung der
definierten Stoppbedingungen. Der Stopp einer Applikation, die Stoppbedingung für eine
Applikation auf einem anderen Rechner darstellt, wird von Start/Stopp über ein entsprechendes
Telegramm mitgeteilt.

****
*Sys-StSt-34* Stoppen Kernsystem
****

* Stoppen des Kernsystems (damit muss auch die Start-/Stopp-Applikation beendet werden).
Dies geschieht in umgekehrter Reihenfolge in Bezug auf den Startvorgang. Es findet kein
Informationsaustausch mit den Start/Stopp-Applikationen auf anderen Rechnern mehr statt.

****
*Sys-StSt-35 (TSys-7)* Start-/Stopp-Reihenfolge
****

Für den Start und Stopp des Kernsystems ist die definierte Reihenfolge bindend. Für alle
anderen Applikationen ergibt sich die Reihenfolge nur über die Start-/Stopp-Bedingungen.
Eine explizite Angabe der Start-/Stopp-Reihenfolge gibt es nicht, auch keine implizite über die
Reihenfolge in der Konfigurationsdatei.

****
*Sys-StSt-36* Start/Stopp auf verschiedenen Rechnern
****

Die verwalteten Applikationen müssen koordiniert auch auf verschiedenen Rechnern
gestartet und gestoppt werden können. Die Start- und Stopp-Bedingungen müssen ebenfalls
verschiedene Rechner berücksichtigen.

****
*Sys-StSt-37* Erkennung von Zyklen
****

Wenn sich durch die Start-/Stopp-Bedingungen Zyklen im Start-/Stopp-Vorgang ergeben,
sind diese zu erkennen. Wenn Zyklen erkannt werden, darf das System nicht gestartet werden.
Eine entsprechende Meldung ist auf der Standardfehlerausgabe abzusetzen.

****
*Sys-StSt-38 (TSys-8)* Kein Aufruf von Start/Stopp selbst
****

Die Start-/Stopp-Applikation selbst darf nicht in der Start-/Stopp-Konfiguration aufgerufen
werden. Hierzu ist sicher zu stellen, dass Start/Stopp nicht startet, wenn auf dem entsprechenden
Rechner bereits eine Applikation mit dem gleichen Klassennamen läuft. Falls die Applikation selbst
aufgerufen werden soll, ist eine entsprechende Meldung ist auf der Standardfehlerausgabe
abzusetzen.

****
*Sys-StSt-39 (TSys-9)* Betriebsmeldung beim Starten oder Stoppen
****

Start/Stopp muss eine Betriebsmeldung absetzen, aus der hervorgeht, dass eine
Applikation gestartet oder gestoppt wurde. In der Betriebsmeldung muss der zugehörige
Zeitstempel enthalten sein.
----
Applikation KEx TLS gestartet. [Sys-StSt-St01]
Applikation KEx TLS gestoppt. [Sys-StSt-St02]
Applikationskennung Start/Stopp
ID AOE
Meldungstyp System
Meldungstyp-Zusatz [Sys-StSt-St<nn>]
Meldungsklasse Information
Referenz Rechner
----

Die fett markierten Anteile sind entsprechend den tatsächlichen Gegebenheiten je Meldung
anzupassen.

****
*Sys-StSt-40 (TSys-10)* Statusinformationen
****

Die Applikation muss alle Statusinformationen der anderen Applikationen, die von ihr
verwaltet werden, zur Verfügung stellen. Zum einen müssen diese Informationen nach
Abarbeitung einer Konfiguration über Telegramme publiziert werden, zum anderen müssen
Veränderungen dieses Zustands (insbesondere das Beenden einer Applikation) mitgeteilt werden.
Die notwendigen Statusinformationen sind:

* Startart (automatisch, manuell, Intervall (incl. Zeitspezifikation))
* Status (angelegt, initialisiert, gestartet, gestoppt)
* Nachstartstatus (wird nachgestartet, wird nicht nachgestartet)

****
*Sys-StSt-41 (TSys-11, 12)* Fehlermeldungen beim Starten und Stoppen
****

Beim Starten von Applikationen sind folgende Fehlerfälle zu erkennen:

* Nicht genügend Speicher, um Applikation zu starten
* Angegebene Datei/Klasse nicht gefunden

Beim Stoppen von Applikationen sind folgende Fehlerfälle zu erkennen:

* Angegebene Datei/Klasse nicht gefunden

In allen Fällen ist eine entsprechende Ausgabe auf die Standardfehlerausgabe durchzuführen.

****
*Sys-StSt-42* Zyklische Ausführung von Applikationen
****

Start/Stopp muss die Möglichkeit bieten, Applikationen zyklisch zu starten. Zur Steuerung
der Zykluszeit muss die cron-Syntax genutzt werden. Es muss außerdem definiert werden können,
ob der Zyklus relativ zum Startzeitpunkt von Start/Stopp ausgeführt wird oder absolut.
Beispielsweise muss eine Applikation entweder jede Stunde nach dem Start von Start/Stopp
ausgeführt werden oder alternativ zu jeder vollen (Zeit-)Stunde.

****
*Sys-StSt-43* Erneute Ausführung einer Konfiguration
****

Start/Stopp muss die Möglichkeit bieten, eine Konfiguration erneut auszuführen, ohne dass
die Start/Stopp-Applikation beendet und neu gestartet werden muss. Die erneute Ausführung
muss in zwei Varianten möglich sein:
* Alle Applikationen, die in der Konfiguration enthalten sind und (noch) laufen, werden zunächst
gestoppt. Danach wird die gesamte Konfiguration neu gestartet.
* Nur die Applikationen in der Konfiguration, die nicht laufen, werden neu gestartet.

****
*Sys-StSt-44 (Sys-7)* Manueller Start/Stopp
****

Einzelne Applikationen müssen manuell gestartet und gestoppt werden können. Es muss
auch möglich sein, Applikationen in einem Arbeitsschritt zu stoppen und gleich wieder zu starten
(„Neustart“).

****
*Sys-StSt-45* Steuerung über Telegramme
****

Einzelne Applikationen müssen auch über Telegramme gestartet und gestoppt werden
können. Beispielsweise muss die USV bei Erreichen eines kritischen Zustands Applikationen
stoppen können oder die Simulation muss Applikationen starten und stoppen können.

****
*Sys-StSt-46* Verwendung der Terminierungsschnittstelle
****

Start/Stopp muss zum Beenden von Applikationen die Terminierungsschnittstelle des
Datenverteilers nutzen, um die Applikationen kontrolliert beenden zu können. Die Applikationen
dürfen nicht mit Hilfe des Betriebssystems „hart“ beendet werden. Dadurch wird sichergestellt,
dass auch Prozesse, die längere Zeit zum Beenden benötigen, ausreichend Zeit haben, alle
notwendigen Schritte durchzuführen und so einen Datenverlust wirksam zu verhindern.

****
*Sys-StSt-47* Keep-alive-Signalisierung
****

Start/Stopp muss regelmäßig eine Rückmeldung geben, dass die Applikation noch läuft.
Wenn die Abarbeitung einer Konfiguration oder auch das Starten oder Stoppen einer einzelnen
Applikation längere Zeit benötigt, muss regelmäßig eine Signalisierung erfolgen, dass erkennbar
ist, dass die Start/Stopp-Applikation selbst noch korrekt arbeitet.

****
*Sys-StSt-48* Bearbeitung der Konfiguration im laufenden Betrieb
****

Es muss möglich sein, im laufenden Betrieb neue Applikationen in Start/Stopp
aufzunehmen. Es muss ebenfalls möglich sein, im laufenden Betrieb eine gestoppte
Applikation aus der Konfiguration zu entfernen. Hierzu zählt auch das Hinzufügen und
Entfernen einer zusätzlichen Inkarnation einer Applikation. Vor der Aktivierung dieser Änderung
muss diese versioniert werden.

****
*Sys-StSt-49* Änderung von Aufrufparametern im laufenden Betrieb
****

Es muss möglich sein, Aufrufparameter einer Applikation im laufenden Betrieb zu ändern,
ohne dass dazu Start/Stopp neu gestartet werden muss. Zu den Aufrufparametern zählen sowohl
Java-Argumente als auch Applikationsargumente. Zur Änderung der Aufrufparameter zählt auch
das Hinzufügen oder Entfernen von Aufrufparametern. Vor der Aktivierung dieser Änderung muss
diese versioniert werden.

****
*Sys-StSt-50* Steuerung über externe Schnittstelle
****

Start/Stopp muss über eine Schnittstelle nach außen verfügen, über die es vollständig von
außen gesteuert werden kann. Vollständig bedeutet, dass alle Funktionen, die intern genutzt
werden können, auch über die Schnittstelle angesprochen werden können. Dadurch wird es
möglich, Start/Stopp in übergeordnete Systeme (Betriebssystem, Leitsysteme) zu integrieren. Die
Schnittstelle muss zusätzlich mindestens über folgende Eigenschaften verfügen:

* Die Schnittstelle muss über einen Zugangsschutz verfügen.
* Die Schnittstelle muss eine verschlüsselte Verbindung nutzen.
* Die Schnittstelle muss über ein Netzwerk ansprechbar sein.
* Die Schnittstelle muss aus anderen Programmen (auch Nicht-Java) heraus ansprechbar sein.

****
*Sys-StSt-51* Robustheit
****

Start/Stopp muss robust sein gegenüber Problemen von zu startenden, zu stoppenden oder
laufenden Applikationen. Probleme in den verwalteten Applikationen dürfen trotz deren
Überwachung nicht dazu führen, dass Start/Stopp selbst instabil wird.

****
*Sys-StSt-52* Auflösung von inkonsistenten Zuständen
****

Start/Stopp muss in der Lage sein, auch inkonsistente Zustände der verwalteten
Applikationen auflösen zu können. Beispielsweise ist es denkbar, dass eine Applikation durch
einen internen Fehler in einem undefinierten Zwischenzustand hängen bleibt. Dann muss
Start/Stopp die Möglichkeit bieten, diese Applikation dennoch zu beenden (oder neu zu starten).
Hierbei müssen von der Applikation signalisierte Zustände ignoriert werden; beispielsweise muss
eine gestoppte Applikation immer gestoppt werden können.

****
*Sys-StSt-53* Sicherheitsvorkehrung beim Beenden
****

Wenn Start/Stopp von außen beendet wird (beispielsweise durch das Betriebssystem), muss
ein Sicherheitsmechanismus greifen. Dieser Mechanismus sorgt dafür, dass zunächst alle von
Start/Stopp verwalteten Applikationen beendet werden, bevor Start/Stopp selbst beendet wird
(Shutdown-Hook).

****
*Sys-StSt-54* Keine Voraussetzungen an das Betriebssystem
****

Start/Stopp darf keine Voraussetzungen an das Betriebssystem hinsichtlich notwendiger
Werkzeuge machen. Wenn spezielle Protokolle (wie beispielsweise Telnet) benötigt werden,
müssen diese über eine eigene Bibliothek zur Verfügung gestellt werden.

==== Funktionale Anforderungen an die Bedienoberfläche

****
*Sys-StSt-55* Textbasierte Oberfläche mit Fenstertechnologie
****

Start/Stopp muss über eine textbasierte Oberfläche mit Fenstertechnologie genutzt und
bedient werden können. Die Oberfläche muss sich am Stil von htop in Linux orientieren. Da
Start/Stopp regelmäßig auf Servern läuft, kann dort nicht die Existenz einer grafischen Oberfläche
vorausgesetzt werden. Um Start/Stopp dennoch komfortabel nutzen zu können, wird eine
textbasierte Oberfläche gefordert. Möglich verfügbare Bibliotheken, die hierfür genutzt werden
können sind „JCurses (Java Curses)“ oder „CHARVA“. Die Bedienung ist als eigene Applikation zu
realisieren, die die Schnittstelle von Start/Stopp nutzt. Die Bedienoberfläche ist „sstop“ zu nennen.

****
*Sys-StSt-56* Oberfläche unabhängig von Applikation
****

Die Bedienoberfläche der Applikation muss unabhängig von der Applikation gestartet und
beendet werden können. Eine Beendigung der Oberfläche darf nicht zur Beendigung der
eigentlichen Start/Stopp-Applikation führen. Wenn Start/Stopp über die Oberfläche beendet wird,
wird das gesamte verwaltete System gestoppt. Nach Abschluss des Stoppvorgangs wird als letztes
die Bedienoberfläche beendet.

****
*Sys-StSt-57* Anzeige der Applikationszustände
****

Die Bedienoberfläche muss in ihrem Hauptfenster die verwalteten Applikationen mit ihrem
aktuellen Zustand anzeigen. Wenn sich der Zustand der Applikationen ändert, muss die
Oberfläche automatisch aktualisiert werden.

****
*Sys-StSt-58* Anzeige der Applikationsdetails
****

Die Bedienoberfläche muss die Detailinformationen für die einzelnen Applikationen auf
Anforderung in einem eigenen Fenster darstellen.

****
*Sys-StSt-59* Starten, Stoppen der Applikationen
****

Die Bedienoberfläche muss das manuelle Stoppen, Starten und Neustarten von
Applikationen ermöglichen. Hierzu zählt das erneute Starten einer gesamten Konfiguration in
den beiden Varianten. Kritische Operationen (Stoppen, Neustarten) müssen mit einem
Bestätigungsdialog abgesichert werden.

****
*Sys-StSt-60* Verwendung der Funktionstasten
****

Die Bedienoberfläche muss die Funktionstasten F1 bis F10 für häufig benötigte oder
typische Funktionen (Stoppen, Starten, Neustarten, Versionieren) nutzen. Hierzu zählt das
erneute Starten einer gesamten Konfiguration in den beiden Varianten sowie das manuelle Starten,
Stoppen und Neustarten von einzelnen Applikationen.

****
*Sys-StSt-61* Farbige Darstellung
****

Die Bedienoberfläche muss die Zustände der verwalteten Applikationen farbig darstellen
können. Der Anwender muss ein- und ausschalten können, ob er die farbige Darstellung
verwenden will. Standardmäßig ist die farbige Darstellung ausgeschaltet.

****
*Sys-StSt-62* Hinzufügen, Entfernen von Applikationen
****

Die Bedienoberfläche muss das Hinzufügen von neuen oder das Entfernen vorhandener
(gestoppter) Applikationen durch einen Dialog unterstützen. Hierzu zählt auch das Hinzufügen
und Entfernen von weiteren Inkarnationen einer Applikation.

****
*Sys-StSt-63* Bearbeitung der Konfiguration
****

Die Bedienoberfläche muss die Änderung, das Hinzufügen und das Entfernen der Elemente
des globalen Abschnitts und des applikationsspezifischen Abschnitts der Start-/Stopp-
Konfiguration in einem Dialog unterstützen.

****
*Sys-StSt-64* Bearbeitung der Aufrufparameter
****

Die Bedienoberfläche muss die Änderung, das Hinzufügen und das Entfernen von
Aufrufparametern durch einen Dialog unterstützen.

****
*Sys-StSt-65* Signatur für Änderungen
****

Die Bedienoberfläche muss durch eine Signatur darstellen, ob die Konfiguration (noch)
nicht-versionierte Änderungen enthält.

****
*Sys-StSt-66* Versionierung
****

Die Bedienoberfläche muss die Versionierung einer Konfiguration unterstützen. Dabei muss
die Eingabe der für die Versionierung notwendigen Informationen durch einen Dialog
unterstützt werden. Änderungen an der Start-/Stopp-Konfiguration durch einen Anwender über
die Oberfläche werden zunächst gesammelt. Erst wenn der Anwender alle Änderungen
durchgeführt hat, veranlasst er die Speicherung und dadurch (automatisch) die Versionierung der
Konfiguration. Außerdem muss die Versionierung nach einer Änderung durch einen externen
Editor unterstützt werden.

****
*Sys-StSt-67* Anzeige von Fehlern
****

Die Bedienoberfläche muss die von Start/Stopp zu erkennenden Fehlerfälle beim Starten
und Stoppen sowie die Erkennung von Zyklen, die auf die Standardfehlerausgabe
geschrieben werden, in einem Fenster anzeigen.

****
*Sys-StSt-68* Schalter für Betriebsmeldungen
****

Der Anwender muss unabhängig vom Startparameter der Start-/Stopp-Applikation die
Erzeugung von Betriebsmeldungen ein- und ausschalten können. Als Standard ist der Wert
des Aufrufparameters zu verwenden. Der Zustand des Schalters muss in der Oberfläche
visualisiert werden; je nach gewählter Darstellung durch Farben (grün/rot) oder durch eine
Signatur.

****
*Sys-StSt-69* Keep-alive-Signalisierung
****

Die Bedienoberfläche muss die regelmäßige Signalisierung von Start/Stopp, dass es noch
läuft, geeignet visualisieren. Wenn die Abarbeitung einer Konfiguration oder das Starten oder
Stoppen einer einzelnen Applikation längere Zeit benötigt, muss auch in der Oberfläche signalisiert
werden, dass Start/Stopp noch korrekt läuft. Außerdem muss die Bedienoberfläche bei der
Abarbeitung längerer Aktionen selbst signalisieren, dass sie noch läuft.

****
*Sys-StSt-70* Abhängigkeitsgraph
****

Die Bedienoberfläche muss die Struktur Start-/Stopp-Konfiguration mit ihren Beziehungen
und Abhängigkeiten grafisch visualisieren (Abhängigkeitsgraph). Denkbar ist eine Darstellung
in einem Koordinatensystem, bei dem eine Achse die Zeit und die andere Achse die jeweilige
Applikation darstellt. Damit können zeitliche Abhängigkeiten deutlich werden und daraus
Optimierungspotenzial durch die Vermeidung von (zu vielen) gleichzeitigen Starts abgeleitet
werden. In dem Abhängigkeitsgraph müssen auf jeden Fall die Start- und Stoppbedingungen
ersichtlich werden. Der Abhängigkeitsgraph für die Startbedingungen kann unabhängig vom
Abhängigkeitsgraph für die Stoppbedingungen angezeigt werden.

=== Qualitätsforderungen

Es gelten die Qualitätsanforderungen gemäß [AFoERZGlobal] ARC-4 bis ARC-9, GLO-18 bis
GLO-22 und GLO-28.

Darüber hinaus gehende Anforderungen an die Qualität werden nicht gestellt.

== Randbedingungen

=== Technische Randbedingungen

==== Programmiersprache

Als Standardprogrammiersprache ist Java 8 oder höher zu verwenden.
NOTE: Es ist in Abstimmung mit dem AG jeweils die im NERZ Systemen aktuell eingesetzte 
      Version zu verwenden. Dies kann eine höhere Version als die aktuell eingesetzte Version Java 8. sein, es
      muss aber nicht immer die letzte aktuell verfügbare Version sein.

=== Organisatorische Randbedingungen

Siehe [AFoERZGlobal]

=== Sonstige Randbedingungen

Siehe [AFoERZGlobal]
